CREATE TABLE customer (
	cID INT(5) Primary Key NOT NULL,
	fName VARCHAR(25) NOT NULL,
	lName VARCHAR(25) NOT NULL,
	DID INT,
	TID INT,
	startDate DATETIME NOT NULL,
	endDate DATETIME NOT NULL,
	FOREIGN KEY DID REFERENCES department.dID,
	FOREIGN KEY TID REFERENCES transaction.tID
);

